name: Cypress

on:
  push:
    paths: ['!*.md']
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
  
    - name: Cypress E2E run
      uses: cypress-io/github-action@v2
      with:
        start: yarn storybook
        wait-on: http://localhost:6006
        browser: chrome
        headless: true
        record: true
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
